on:
  workflow_dispatch: 
  push:
    branches: 
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Get Package Version
        id: package_version
        uses: notiz-dev/github-action-json-property@a5a9c668b16513c737c3e1f8956772c99c73f6e8
        with:
          path: "package.json"
          prop_path: "version"

      - name: Set dst json name
        run: echo "jsonFile=vpm-test-${{ steps.package_version.outputs.prop }}.json" >> $GITHUB_ENV

      - name: Copy package.json
        run: cp package.json ${{ env.jsonFile }}

      - name: Commit package.json
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env: 
          API_TOKEN_GITHUB: ${{ steps.generate_token.outputs.token }}
        with:
          source_file: ${{ env.jsonFile }}
          destination_repo: "raiti-chan/vpm-repo"
          destination_folder: "packages/vpm-test"
          destination_branch: "main"
          destination_branch_create: "release/vpm-test-${{ steps.package_version.outputs.prop }}"
          user_email: "github-actions[bot]@users.noreply.github.com"
          user_name: "github-actions[bot]"
          commit_message: "Release vpm-test ${{ steps.package_version.outputs.prop }}"

      - name: Create Pull Request
        run: |
          gh pr create\
            --title "Release vpm-test ${{ steps.package_version.outputs.prop }}" \
            --body "Release vpm-test ${{ steps.package_version.outputs.prop }}" \
            --repo "raiti-chan/vpm-repo" \
            --base main \
            --head release/vpm-test-${{ steps.package_version.outputs.prop }}
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}